#!/bin/bash

# Change home directory (bower puts a lot of cache and tmp directories here)
HOME=$OPENSHIFT_REPO_DIR
BABEL_DISABLE_CACHE=1

cd ${OPENSHIFT_REPO_DIR}
if [ -d ${TMP}node_modules ]; then
mv -f ${TMP}node_modules ./
fi
npm prune --production
npm i --production --loglevel error

npm run build
